name: flutter_faker_plus
description: Generate random fake data for user profiles, e-commerce products, and geolocations etc.
version: 0.0.1
homepage: https://pub.dev/packages/flutter_faker_plus
repository: https://github.com/samieruashovo/flutter_faker_plus
issue_tracker: https://github.com/samieruashovo/flutter_faker_plus/issues
documentation: https://pub.dev/packages/flutter_faker_plus

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
