name: flutter_faker_plus
description: A comprehensive fake data generator for Flutter/Dart applications, created from scratch. Generate random data for user profiles, e-commerce products, and geolocations, with plans for more features like image URLs and fake QR code generation.
version: 0.0.1
homepage: https://pub.dev/packages/flutter_faker_plus

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
